### ISSUE TITLE
Error: Configuration File Not Found

### ISSUE THREAD

**Issue by InikoPro** [ArtichautLearnCode/PterodactylArmInstalationGuide#2]
Can you how to fix this?

root@raspberrypi:/# wings

Error: Configuration File Not Found

Wings was not able to locate your configuration file, and therefore is not
able to complete its boot process. Please ensure you have copied your instance
configuration file into the default location below.

Default Location: /etc/pterodactyl/config.yml

This is not a bug with this software. Please do not make a bug report
for this issue, it will be closed.

root@raspberrypi:/#

**Comment by ArtichautDev** [comment]
You need to deploy the node with the script in the panel or create the /etc/pterodactyl/config.yml file

(Node configuration (deploy) on the panel)
